using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Ai_Enemy : PawnScript
{

    private Vector3 VtoPlayer;
    public GameObject gun; 

    public void Spawn() //Spawns AI at coordinate generated by random bullshit below 
    {
        

        Vector3 spawnPoint = new Vector3(Random.Range(-10,10), 0, Random.Range(-10,10));
        transform.position = spawnPoint;

    }

    public void GivePlayerLocation(Vector3 P_Location) //Called to update the Ai on where the player currently is 
    {
        VtoPlayer = P_Location - this.transform.position; //This points to the player 
        VtoPlayer.Normalize(); //Normalizes vector to be relative to 1 
    }



    // Start is called before the first frame update
    void Start()
    {    
        movementSpeed = 2;
        base.Start();

    }

    

    // Update is called once per frame
    void Update()
    {

        
        transform.Translate(VtoPlayer * movementSpeed * Time.deltaTime); //move twoard player

        if (coolDown > 0)
        {
            coolDown -= 1;
        }
        else
        {
            Shoot(VtoPlayer);
            coolDown = 150;
            //coolDown = gun.firerate; 
        }




    }
}
